#!/usr/bin/env python3

import argparse
from pathlib import Path

import cv2
import numpy as np

# RealSense RGB ROI for depth comparison
ROI_MIN_X = 510
ROI_MAX_X = 740
ROI_MIN_Y = 140
ROI_MAX_Y = 465

def load_projected_helios(path):
    """
    Load the output generated by project_to_image.py.
    """
    with np.load(path) as data:
        xyz_realsense = np.asarray(data["xyz_realsense"],dtype=np.float32,)

        u = np.asarray(data["u"],dtype=np.int32,)
        v = np.asarray(data["v"],dtype=np.int32,)

    return xyz_realsense, u, v

def load_realsense_depth(path):
    """
    Load float32 RealSense depth TIFF.

    Your capture script already stores depth in metres.
    """
    depth = cv2.imread(str(path),cv2.IMREAD_UNCHANGED,)

    if depth is None:
        raise FileNotFoundError(f"Could not read depth image: {path}")

    depth = np.asarray(depth,dtype=np.float32,)

    return depth

def z_buffer_indices(
    xyz,
    u,
    v,
    image_width,
):
    """
    Keep nearest Helios point when multiple points
    project to the same RealSense pixel.
    """

    pixel_id = (v.astype(np.int64) * image_width + u.astype(np.int64))

    # Sort nearest Z first.
    order = np.argsort(xyz[:, 2])
    sorted_pixel_id = pixel_id[order]

    _, first = np.unique(
        sorted_pixel_id,
        return_index=True,
    )

    return order[first]

def compare_depth(
    xyz,
    u,
    v,
    realsense_depth,
):
    height, width = realsense_depth.shape[:2]

    # Make sure projected pixels are inside depth image.
    inside_image = (
        (u >= 0)
        & (u < width)
        & (v >= 0)
        & (v < height)
    )

    # Keep only points inside the calibration ROI
    inside_roi = (
        (u >= ROI_MIN_X)
        & (u < ROI_MAX_X)
        & (v >= ROI_MIN_Y)
        & (v < ROI_MAX_Y)
    )

    inside = inside_image & inside_roi

    xyz = xyz[inside]
    u = u[inside]
    v = v[inside]

    # --------------------------------------------------
    # Z-buffer Helios points
    # --------------------------------------------------
    coverage_before = np.zeros(
        (height, width),
        dtype=np.uint8,
    )

    coverage_before[v, u] = 255

    coverage_before_roi = coverage_before[
        ROI_MIN_Y:ROI_MAX_Y,
        ROI_MIN_X:ROI_MAX_X,
    ]

    cv2.imwrite(
        "/home/support/unseen_sku_ws/outputs/helios_coverage_before_zbuffer_roi.png",
        coverage_before_roi,
    )

    keep = z_buffer_indices(xyz, u, v, width,)

    xyz = xyz[keep]
    u = u[keep]
    v = v[keep]

    coverage = np.zeros(
        (height, width),
        dtype=np.uint8,
    )

    coverage[v, u] = 255

    coverage_roi = coverage[
        ROI_MIN_Y:ROI_MAX_Y,
        ROI_MIN_X:ROI_MAX_X,
    ]

    cv2.imwrite(
        "/home/support/unseen_sku_ws/outputs/helios_coverage_roi.png",
        coverage_roi,
    )

    # --------------------------------------------------
    # Sample RealSense depth
    # --------------------------------------------------

    rs_depth = realsense_depth[v, u]
    helios_depth = xyz[:, 2]

    # Only compare valid RealSense depth pixels.
    valid = (
        np.isfinite(rs_depth)
        & (rs_depth > 0.0)
        & np.isfinite(helios_depth)
        & (helios_depth > 0.0)
    )

    rs_depth = rs_depth[valid]
    helios_depth = helios_depth[valid]

    u = u[valid]
    v = v[valid]

    # Signed error:
    #
    # positive:
    # Helios point is farther away than RealSense depth
    #
    # negative:
    # Helios point is closer than RealSense depth
    signed_error_m = helios_depth - rs_depth
    absolute_error_m = np.abs(signed_error_m)

    return (
        u,
        v,
        helios_depth,
        rs_depth,
        signed_error_m,
        absolute_error_m,
    )

def print_statistics(
    absolute_error_m,
    signed_error_m,
):
    error_mm = absolute_error_m * 1000.0
    signed_mm = signed_error_m * 1000.0

    print()
    print("Depth comparison")
    print("================")
    print(
        f"Compared points: "
        f"{len(error_mm)}"
    )

    if len(error_mm) == 0:
        print("No valid depth correspondences.")
        return

    print()
    print("Absolute depth error")
    print("--------------------")

    print(
        f"Mean:      "
        f"{np.mean(error_mm):.2f} mm"
    )

    print(
        f"Median:    "
        f"{np.median(error_mm):.2f} mm"
    )

    print(
        f"75th pct:  "
        f"{np.percentile(error_mm, 75):.2f} mm"
    )

    print(
        f"90th pct:  "
        f"{np.percentile(error_mm, 90):.2f} mm"
    )

    print(
        f"95th pct:  "
        f"{np.percentile(error_mm, 95):.2f} mm"
    )

    print()
    print("Signed depth error")
    print("------------------")

    print(
        f"Mean bias: "
        f"{np.mean(signed_mm):.2f} mm"
    )

    print()
    print("Agreement")

    for threshold_mm in (
        5,
        10,
        20,
        30,
        50,
    ):
        percentage = (
            np.mean(
                error_mm <= threshold_mm
            )
            * 100.0
        )

        print(
            f" <= {threshold_mm:2d} mm: "
            f"{percentage:6.2f}%"
        )


def make_error_overlay(
    rgb,
    u,
    v,
    absolute_error_m,
    output_path,
):
    """
    Draw projected points coloured by absolute
    Helios-vs-RealSense depth difference.
    """

    overlay = rgb[
        ROI_MIN_Y:ROI_MAX_Y,
        ROI_MIN_X:ROI_MAX_X,
    ].copy()

    # Convert global image coordinates to ROI coordinates
    u_roi = u - ROI_MIN_X
    v_roi = v - ROI_MIN_Y

    error_mm = absolute_error_m * 1000.0
    # Cap colour scaling at 50 mm.
    max_error_mm = 50.0

    normalized = np.clip(
        error_mm / max_error_mm,
        0.0,
        1.0,
    )

    error_u8 = (normalized * 255).astype(np.uint8)

    colours = cv2.applyColorMap(
        error_u8.reshape(-1, 1),
        cv2.COLORMAP_TURBO,
    ).reshape(-1, 3)

    # Limit number of visible dots.
    max_points = 30000

    step = max(1, len(u) // max_points)

    for i in range(0, len(u), step):

        px = int(u_roi[i])
        py = int(v_roi[i])
        colour = tuple(
            int(x) for x in colours[i]
        )

        cv2.circle(
            overlay,
            (px,py),
            1,
            colour,
            -1,
        )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True,)

    cv2.imwrite(str(output_path), overlay,)

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Compare projected Helios depth "
            "against aligned RealSense depth."
        )
    )

    parser.add_argument(
        "--projected",
        required=True,
        help=(
            "Output NPZ from project_to_image.py"
        ),
    )

    parser.add_argument(
        "--depth",
        required=True,
        help=(
            "RealSense aligned depth TIFF stored in metres."
        ),
    )

    parser.add_argument(
        "--rgb",
        default=None,
        help=(
            "Optional RealSense RGB image for error visualization."
        ),
    )

    parser.add_argument(
        "--overlay",
        default=None,
        help=(
            "Optional depth-error overlay output."
        ),
    )

    parser.add_argument(
        "--output",
        default="depth_comparison.npz",
        help="Output comparison NPZ.",
    )

    args = parser.parse_args()

    xyz, u, v = load_projected_helios(args.projected)

    realsense_depth = load_realsense_depth(args.depth)

    (
        u,
        v,
        helios_depth,
        rs_depth,
        signed_error,
        absolute_error,
    ) = compare_depth(
        xyz,
        u,
        v,
        realsense_depth,
    )

    print_statistics(absolute_error, signed_error)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True,)

    np.savez(
        output_path,
        u=u,
        v=v,
        helios_depth_m=helios_depth,
        realsense_depth_m=rs_depth,
        signed_error_m=signed_error,
        absolute_error_m=absolute_error,
    )

    print()
    print(
        f"Saved comparison: "
        f"{output_path.resolve()}"
    )

    if (args.rgb is not None and args.overlay is not None):
        rgb = cv2.imread(args.rgb, cv2.IMREAD_COLOR,)

        if rgb is None:
            raise FileNotFoundError(
                f"Could not read RGB image: "
                f"{args.rgb}"
            )

        make_error_overlay(
            rgb,
            u,
            v,
            absolute_error,
            args.overlay,
        )

        print(
            f"Saved error overlay: "
            f"{Path(args.overlay).resolve()}"
        )

if __name__ == "__main__":
    main()